import type { ElementType } from 'react';
import {
  Apple,
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Bus,
  CakeSlice,
  Calculator,
  Car,
  ChartNoAxesCombined,
  CircleDollarSign,
  Cloud,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Droplets,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  HousePlus,
  Landmark,
  Laptop,
  Leaf,
  Medal,
  MoreHorizontal,
  Music,
  NotebookPen,
  PartyPopper,
  PawPrint,
  Pencil,
  PiggyBank,
  Pizza,
  Plane,
  Plus,
  Receipt,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  Sun,
  Target,
  Train,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react';

export interface CategoryIconOption {
  name: string;
  label: string;
  Icon: ElementType;
}

export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = [
  { name: 'Wallet', label: 'Dompet', Icon: Wallet },
  { name: 'Banknote', label: 'Uang Tunai', Icon: Banknote },
  { name: 'CircleDollarSign', label: 'Pemasukan', Icon: CircleDollarSign },
  { name: 'TrendingUp', label: 'Investasi', Icon: TrendingUp },
  { name: 'BriefcaseBusiness', label: 'Bisnis', Icon: BriefcaseBusiness },
  { name: 'Briefcase', label: 'Pekerjaan', Icon: Briefcase },
  { name: 'Laptop', label: 'Freelance', Icon: Laptop },
  { name: 'Building', label: 'Kantor', Icon: Building },
  { name: 'Landmark', label: 'Bank', Icon: Landmark },
  { name: 'Coins', label: 'Koin', Icon: Coins },
  { name: 'PiggyBank', label: 'Tabungan', Icon: PiggyBank },
  { name: 'Target', label: 'Target', Icon: Target },
  { name: 'HousePlus', label: 'Rumah', Icon: HousePlus },
  { name: 'Home', label: 'Hunian', Icon: Home },
  { name: 'Utensils', label: 'Makanan', Icon: Utensils },
  { name: 'Coffee', label: 'Kopi', Icon: Coffee },
  { name: 'Pizza', label: 'Kuliner', Icon: Pizza },
  { name: 'Apple', label: 'Groceries', Icon: Apple },
  { name: 'CakeSlice', label: 'Camilan', Icon: CakeSlice },
  { name: 'Cookie', label: 'Snack', Icon: Cookie },
  { name: 'ShoppingBag', label: 'Belanja', Icon: ShoppingBag },
  { name: 'ShoppingCart', label: 'Kebutuhan', Icon: ShoppingCart },
  { name: 'Shirt', label: 'Pakaian', Icon: Shirt },
  { name: 'Car', label: 'Mobil', Icon: Car },
  { name: 'Fuel', label: 'Bensin', Icon: Fuel },
  { name: 'Bus', label: 'Bus', Icon: Bus },
  { name: 'Train', label: 'Kereta', Icon: Train },
  { name: 'Bike', label: 'Sepeda', Icon: Bike },
  { name: 'Plane', label: 'Perjalanan', Icon: Plane },
  { name: 'Receipt', label: 'Tagihan', Icon: Receipt },
  { name: 'CreditCard', label: 'Kartu', Icon: CreditCard },
  { name: 'Wifi', label: 'Internet', Icon: Wifi },
  { name: 'Smartphone', label: 'Gadget', Icon: Smartphone },
  { name: 'Zap', label: 'Listrik', Icon: Zap },
  { name: 'Droplets', label: 'Air', Icon: Droplets },
  { name: 'Heart', label: 'Kesehatan', Icon: Heart },
  { name: 'Stethoscope', label: 'Medis', Icon: Stethoscope },
  { name: 'Dumbbell', label: 'Olahraga', Icon: Dumbbell },
  { name: 'GraduationCap', label: 'Pendidikan', Icon: GraduationCap },
  { name: 'BookOpen', label: 'Buku', Icon: BookOpen },
  { name: 'NotebookPen', label: 'Kursus', Icon: NotebookPen },
  { name: 'Pencil', label: 'Alat Tulis', Icon: Pencil },
  { name: 'Calculator', label: 'Pajak', Icon: Calculator },
  { name: 'Gamepad2', label: 'Game', Icon: Gamepad2 },
  { name: 'Music', label: 'Musik', Icon: Music },
  { name: 'Film', label: 'Film', Icon: Film },
  { name: 'Tv', label: 'TV', Icon: Tv },
  { name: 'Headphones', label: 'Audio', Icon: Headphones },
  { name: 'PartyPopper', label: 'Acara', Icon: PartyPopper },
  { name: 'Gift', label: 'Hadiah', Icon: Gift },
  { name: 'Shield', label: 'Proteksi', Icon: Shield },
  { name: 'Umbrella', label: 'Darurat', Icon: Umbrella },
  { name: 'Users', label: 'Keluarga', Icon: Users },
  { name: 'Baby', label: 'Anak', Icon: Baby },
  { name: 'PawPrint', label: 'Hewan', Icon: PawPrint },
  { name: 'Leaf', label: 'Lingkungan', Icon: Leaf },
  { name: 'Sun', label: 'Liburan', Icon: Sun },
  { name: 'Cloud', label: 'Langganan', Icon: Cloud },
  { name: 'Star', label: 'Favorit', Icon: Star },
  { name: 'Trophy', label: 'Prestasi', Icon: Trophy },
  { name: 'Medal', label: 'Tujuan', Icon: Medal },
  { name: 'Wrench', label: 'Servis', Icon: Wrench },
  { name: 'ChartNoAxesCombined', label: 'Portofolio', Icon: ChartNoAxesCombined },
  { name: 'Plus', label: 'Lainnya', Icon: Plus },
  { name: 'MoreHorizontal', label: 'Umum', Icon: MoreHorizontal },
  { name: 'Wine', label: 'Santai', Icon: Wine },
];

const CATEGORY_ICON_MAP = Object.fromEntries(
  CATEGORY_ICON_OPTIONS.map((option) => [option.name, option.Icon])
) as Record<string, ElementType>;

export const CATEGORY_ICON_NAMES = CATEGORY_ICON_OPTIONS.map((option) => option.name);

export function getCategoryIconComponent(iconName: string) {
  return CATEGORY_ICON_MAP[iconName] ?? MoreHorizontal;
}

export function isCategoryIconName(iconName: string) {
  return CATEGORY_ICON_NAMES.includes(iconName);
}
